# Generated by Django 5.1.7 on 2025-03-28 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carbon", "0002_alter_modelo_carbon_manufactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name="Ativos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=255)),
                ("has_engine", models.BooleanField()),
                ("can_tow", models.BooleanField()),
                ("can_be_towed", models.BooleanField()),
                ("fg_operate", models.BooleanField(default=False)),
                ("fg_product_transport", models.BooleanField(default=False)),
                ("engine_power", models.FloatField(default=0)),
                ("working_speed", models.FloatField(default=0)),
                ("working_width", models.FloatField(default=0)),
                ("hor_init", models.FloatField(default=0)),
                ("km_init", models.FloatField(default=0)),
                ("hor_current", models.FloatField(default=0)),
                ("km_current", models.FloatField(default=0)),
                ("avg_fuel_consumption", models.FloatField(default=0)),
                (
                    "modelo_carbon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carbon.modelo_carbon",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cdata.org"
                    ),
                ),
            ],
        ),
    ]
