# Generated by Django 5.1.7 on 2025-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdata", "0002_alter_ativos_avg_fuel_consumption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativos",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="org",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="ativos",
            unique_together={("org", "name"), ("org", "oid")},
        ),
    ]
