# Generated by Django 5.1.7 on 2025-03-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdata", "0003_ativos_name_org_name_alter_ativos_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativos",
            name="working_speed",
        ),
    ]
