# Generated by Django 5.1.7 on 2025-03-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Modelo_Carbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("has_engine", models.BooleanField()),
                ("can_tow", models.BooleanField(default=False)),
                ("can_be_towed", models.BooleanField(default=False)),
                (
                    "manufactor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carbon.manufactor",
                    ),
                ),
            ],
            options={
                "unique_together": {("manufactor", "name")},
            },
        ),
    ]
