# Generated by Django 5.1.7 on 2025-03-28 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelo_carbon",
            name="manufactor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="carbon.manufactor"
            ),
        ),
    ]
